version: "3.8"

services:
  mongo:
    image: mongo:4.2
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    env_file:
      - ./.env
